version: '3.8'

services: 
  postgresSQLDatabase:
      image: postgres:latest
      container_name: postgresDB
      volumes: 
       - postgresVolume:/var/lib/postgresql/data/
      restart: always
      environment:
        POSTGRES_USER: kosev
        POSTGRES_PASSWORD: root
        POSTGRES_DB: anonimnobg
      ports: 
       - 5432:5432
volumes:
  postgresVolume:
      name: postgres_volume
      external: false