version: '3.8'

services: 
  postgresSQLDatabase:
      image: postgres:latest
      container_name: idm-postgres
      volumes: 
       - postgresVolume:/var/lib/postgresql/data/
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: admin123
        POSTGRES_DB: idm
      ports: 
       - 5432:5432
volumes:
  postgresVolume:
      name: idm-postgres-data
      external: false