version: '3.8'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    environment:
        POSTGRES_USER: kosev
        POSTGRES_PASSWORD: root
        POSTGRES_DB: anonimnobg
    ports:
      - 5432:5432
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    networks:
      - postgres-network
    restart: always
  
  pgadmin:
    container_name: postgres-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: veliko.kosev@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - postgres-network
    volumes: 
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 5050:80
    restart: on-failure
    depends_on:
      - postgres-db


volumes:
  postgres-db-data:
    name: postgres-db-data
    driver: local

  pgadmin-data:
    name: pgadmin-data
    driver: local

networks:
  postgres-network:
    name: postgres-network